title: Little Giants
email: littlegiantsbe@gmail.com
description: >-
  We are Little Giants, a Belgian esports team focused on Counter-Strike 2.
  Whether we're practicing, competing, or connecting with our community,
  our goal is simple: to keep improving and to play at the highest level.

  Join us on our journey as we push our limits, take on new challenges, and aim for victory.
  Stay updated with our latest matches, streams, and team news.

  Game. Compete. Grow.
baseurl: ""
url: ""
discord: jCG3EF5fJs

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
