title: Little Giants
email: littlegiantsbe@gmail.com
description: >-
  Belgian Counter-Strike 2 esports team
baseurl: ""
url: ""
discord: jCG3EF5fJs
logo: assets/img/logo.png

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
